### PR TITLE
Update nouns.json

### PR DESCRIPTION
**Pull request by encosllo**
A few more entries.

### CODE REVIEW

**Comment by thosgood** [comment]
this is incredible work — thank you! you've even got the wikidata tags ☺️

**Comment by encosllo** [comment]
You're welcome! It is very nice to see the wikidata tag! Nice idea.
Feel free to merge this update in your own branch. 
 
If I may add a few suggestions, I think there are some features that would be interesting to implement.
It would be nice to see adjectives, verbs, adverbs and connectors as well, not only nouns. Take for example "to abelianize", "to lift", "to expand", ... "coherent", "complete", ... "smoothly", ... "if and only if"...
Would it be possible to add some fields in every noun pointing to the adjectives that can accompany it and other nouns that are synonyms?

In the main webpage, it would be nice to see the words alphabetically ordered according to a given language or some search engine that returns only the desired word and the associated fields.

Take these as suggestions, not obligations. Thanks!

**Comment by thosgood** [comment]
Sorry, I thought I had merged it!

My goal is definitely to expand beyond just nouns, but this is something that I want to do in such a way that we don't run into problems further down the line. This is something I should be able to do in the near future, so I'll let people know when I've got some ideas to put into beta testing.

As for your other suggestions:

- Yes, I want to be able to create stand-alone adjective "families", i.e. a bunch of adjectives that can be applied to multiple nouns (e.g. group, algebra, ring, etc. all share a lot of adjectives), but one thing that has stopped me from doing this right now is that I'm still not 100% sure that all languages *do* use exactly the same sets of adjectives as in English (I'm pretty sure they will, but I just don't know enough about non-European languages to be able to say!).
- You can order a column alphabetically by clicking on the language name in the column header. This isn't at all clear, so I need to add a little icon or description or something, but I have some good reasons to wait until I actually just rebuild the web interface entirely, because this is something that should be done sooner rather than later.
- Search functionality is definitely a vital thing, but I think it might be best to wait until we've figured out how the dictionary will be structured with verbs etc. At the moment I'm just recommending `ctrl+F` to people.

All very useful to hear though. Please don't ever hesitate to suggest anything else! (Maybe open it as a GitHub issue?)

**Comment by encosllo** [comment]
Thank you very much Tim. Very interesting!
I didn't know anything about the alphabetical sorting.
On the first question, I don't know that much about non-European languages either. 
With regard to restructuring the webpage, would it be more useful for you if I stopped sending entries, or would you prefer me to continue with this work? I am afraid that the nouns.json file will grow too big to be useful later.

**Comment by thosgood** [comment]
No, don't worry about that: it doesn't matter to me at all how big the nouns.json file is, so feel free to keep adding to it if you want to!

**Pull request merged**
